name: spicyreads
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.9.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  provider: ^6.1.2

  # Firebase Core
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3
  firebase_analytics:
    ^12.0.3

    # Utility & Navigation
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  go_router: ^16.3.0

  # API/Network & Monetization
  dio: ^5.4.0
  in_app_purchase: ^3.2.3

  # UI Enhancements
  google_fonts: ^6.1.0
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.0.7

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  fake_cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo.png'
